module.exports = {
  notFound: require('./notFound'),
  errorHandler: require('./errorHandler'),
  logger: require('./logger'),
  auth: require('./auth'),
  requestId: require('./requestId'),
  userAuditLogger: require('./userAuditLogger'),
  errorParser: require('./errorParser'),
  rateLimiter: require('./rateLimiter'),
  checkUser: require('./auth/checkUser'),
  adminOnly: require('./adminOnly'),
  userAgent: require('./userAgent'),
  swagger: require('./swagger'),
  slugValidator: require('./slugValidator'),
};
