openapi: 3.0.0
info:
  title: Resume Builder Pro API
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
paths:
  /resumes:
    get:
      summary: List resumes
      responses:
        '200':
          description: OK
    post:
      summary: Create resume
      responses:
        '201':
          description: Created
